# Generated by Django 5.1.1 on 2024-10-28 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_number", models.CharField(max_length=20)),
                ("question", models.TextField()),
                ("selected_answer", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Violator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compliance", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="violators/"),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=255,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
