# Generated by Django 5.1.2 on 2024-11-04 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quizresponse_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance', models.CharField(max_length=255, null=True)),
                ('personid', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='violators/')),
                ('action_taken', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Violator',
        ),
    ]
