# Generated by Django 5.1.2 on 2024-11-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_option_question_delete_quizresponse_option_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('selected_answer', models.CharField(max_length=10)),
                ('correct_answer', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='counsling',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='identify_employee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
