# Generated by Django 5.1.2 on 2024-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quizresponse_people_counsling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
