# Generated by Django 5.1.3 on 2024-12-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compliance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compliance',
            new_name='Compliances',
        ),
    ]
